// Generated by CoffeeScript 1.6.1
/*
 * vibox - node.js cli helper for VirtualBox Management
 *
 * COFFEESCRIPT Document - /js/script.js
 * Screen & responsive styles
 * coded by leny@flatLand!
 * started at 09/05/13
*/(function(){var e,t,n,r,i;t=document.querySelectorAll("div.command div.samples nav a");n=function(e){var t,n,r,i,s,o,u,a,f;e.preventDefault();r=e.currentTarget;a=r.parentNode.querySelectorAll("a.active");for(i=0,o=a.length;i<o;i++){n=a[i];n.className=""}f=r.parentNode.parentNode.querySelectorAll(".terminal");for(s=0,u=f.length;s<u;s++){t=f[s];t.style.display="none"}document.getElementById(r.getAttribute("href").replace("#","")).style.display="block";return r.className="active"};for(r=0,i=t.length;r<i;r++){e=t[r];e.addEventListener("click",n)}}).call(this);